### ISSUE TITLE
Install error: /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-1.25.1, already activated mime-types-3.1 (Gem::LoadError)

### ISSUE THREAD

**Issue by benmathews** [telcat/vagrant-proxmox#38]
Can't install w/ vagrant 1.9.1. 

```
$ vagrant plugin install vagrant-proxmox
Installing the 'vagrant-proxmox' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-1.25.1, already activated mime-types-3.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:323:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:320:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:248:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/bundler.rb:98:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/bin/vagrant:127:in `<main>'
```

There is some discussion at https://github.com/ggiamarchi/vagrant-openstack-provider/issues/311 that the vagrant api changed.

**Comment by scottlinux** [comment]
I tested out bumping rest-client as in that openstack fix, but this leaves vagrant-proxmox unable to locate the specified endpoint. (An empty endpoint?)

```
$ vagrant up
Unable to communicate with proxmox server:

undefined method `empty?' for nil:NilClass
```

**Comment by stinnux** [comment]
I had success using the fork from https://github.com/lehn-etracker/vagrant-proxmox. Give it a try!
