### ISSUE TITLE
Fail to install plugin

### ISSUE THREAD

**Issue by Fridus** [telcat/vagrant-proxmox#39]
- Vagrant 1.9.5
- Proxmox 4.4

```sh
# vagrant plugin install vagrant-proxmox
Installing the 'vagrant-proxmox' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-1.25.1, already activated mime-types-3.1 (Gem::LoadError)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/specification.rb:1276:in `activate'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:388:in `block in activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:385:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:385:in `activate_solution'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:288:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:106:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/action/install_gem.rb:29:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/root.rb:66:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:138:in `<main>'
```

**Comment by ghost** [comment]
Same here. Maybe someone can update this. We are currently evaluating ProxMox as underlying server for Kubernetes and would love to use vagrant for quick provisioning.
