### ISSUE TITLE
Fail to install - conflicting dependencies

### ISSUE THREAD

**Issue by jsporna** [telcat/vagrant-proxmox#46]
On Ubuntu 20.04
vagrant from Ubuntu repository: 2.2.6
vagrant from vagrantup.com: 2.2.14

❯ vagrant plugin install vagrant-proxmox
Installing the 'vagrant-proxmox' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies i18n (>= 0.6.4, ~> 0.6) and i18n (= 1.8.2)
  Activated i18n-1.8.2
  which does not match conflicting dependency (>= 0.6.4, ~> 0.6)

  Conflicting dependency chains:
    i18n (= 1.8.2), 1.8.2 activated

  versus:
    vagrant-proxmox (> 0), 0.0.12 activated, depends on
    activesupport (~> 4.0.0), 4.0.0 activated, depends on
    i18n (>= 0.6.4, ~> 0.6)

same error for downloaded gem file

**Comment by BinkyWong** [comment]
I get similar from Windows:

<pre>
PS C:\Users\User> vagrant plugin install vagrant-proxmox
Installing the 'vagrant-proxmox' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies i18n (~> 0.6, >= 0.6.4) and i18n (= 1.8.10)
  Activated i18n-1.8.10
  which does not match conflicting dependency (~> 0.6, >= 0.6.4)

  Conflicting dependency chains:
    i18n (= 1.8.10), 1.8.10 activated

  versus:
    vagrant-proxmox (> 0), 0.0.2 activated, depends on
    activesupport (~> 4.0.0), 4.0.0 activated, depends on
    i18n (~> 0.6, >= 0.6.4)
</pre>

**Comment by borger** [comment]
I believe this repo is abandoned guys, I've managed to get past this error by using https://github.com/lehn-etracker/vagrant-proxmox which has been getting recent updates. However, I did had with other issues (more related to my environment than anything else), and eventually migrated my project to [Terraform](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/guides/installation).

**Comment by stanier** [comment]
Definitely looks like a dead repo :(

**Comment by john-clark** [comment]
New Install of Debian with distribution version of Vagrant
---
`# lsb_release -a`
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
`# apt install vagrant`
`# vagrant -v`
```
Vagrant 2.2.14
```
`# vagrant plugin install vagrant-proxmox`
```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies i18n (>= 0.6.4, ~> 0.6) and i18n (= 1.8.8)
  Activated i18n-1.8.8
  which does not match conflicting dependency (>= 0.6.4, ~> 0.6)

  Conflicting dependency chains:
    i18n (= 1.8.8), 1.8.8 activated

  versus:
    vagrant-proxmox (> 0), 0.0.10 activated, depends on
    activesupport (~> 4.0.0), 4.0.3 activated, depends on
    i18n (>= 0.6.4, ~> 0.6)
```
Install official version of Vagrant
---
`# wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg`
`# echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list`
`# sudo apt update && sudo apt upgrade`
`# vagrant plugin install vagrant-proxmox`
```
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies i18n (>= 0.6.4, ~> 0.6) and i18n (= 1.12.0)
  Activated i18n-1.12.0
  which does not match conflicting dependency (>= 0.6.4, ~> 0.6)

  Conflicting dependency chains:
    i18n (= 1.12.0), 1.12.0 activated

  versus:
    vagrant-proxmox (> 0), 0.0.2 activated, depends on
    activesupport (~> 4.0.0), 4.0.0 activated, depends on
    i18n (>= 0.6.4, ~> 0.6)
```
`# VAGRANT_DISABLE_STRICT_DEPENDENCY_ENFORCEMENT=1 vagrant plugin install vagrant-proxmox --verbose`
```
Installing the 'vagrant-proxmox' plugin. This can take a few minutes...
Traceback (most recent call last):
        23: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/bin/vagrant:248:in `<main>'
        22: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/environment.rb:301:in `cli'
        21: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/cli.rb:67:in `execute'
        20: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/commands/plugin/command/root.rb:66:in `execute'
        19: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/commands/plugin/command/install.rb:69:in `execute'
        18: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/commands/plugin/command/install.rb:69:in `each'
        17: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/commands/plugin/command/install.rb:70:in `block in execute'
        16: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/commands/plugin/command/base.rb:14:in `action'
        15: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
        14: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
        13: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
        12: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
        11: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        10: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/commands/plugin/action/install_gem.rb:30:in `call'
         9: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/plugin/manager.rb:146:in `install_plugin'
         8: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:477:in `verbose'
         7: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
         6: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:355:in `install'
         5: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:593:in `internal_install'
         4: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:753:in `activate_solution'
         3: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:753:in `each'
         2: from /opt/vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/bundler.rb:756:in `block in activate_solution'
         1: from /opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/specification.rb:1369:in `activate'
/opt/vagrant/embedded/lib/ruby/2.7.0/rubygems/specification.rb:2247:in `raise_if_conflicts': Unable to activate rest-client-1.6.14, because mime-types-3.4.1 conflicts with mime-types (~> 1.16) (Gem::ConflictError)
```

**Comment by casperghst42** [comment]
@john-clark did you ever find a solution for this?

**Comment by mthbrown** [comment]
Not sure if this will fix it but [this](https://github.com/lehn-etracker/vagrant-proxmox) fork has had a number of updates over the years while this project hasn't since 2016

**Comment by Raaatus** [comment]
change the version of i18n from ruby.
uninstall and reinstall the desired version
(sudo)

```
gem uninstall -i /usr/share/rubygems-integration/all i18n
gem install i18n --version==0.6.4
vagrant plugin install vagrant-proxmox
```

**Comment by PhilippStrobel** [comment]
The steps above does not solve the issue.
Removing the current version 1.14.1 causes dependency error for vagrant

`# GEM_HOME=/opt/vagrant/embedded/gems/ gem uninstall i18n

You have requested to uninstall the gem:
        i18n-1.14.1

vagrant-2.4.1 depends on i18n (~> 1.12)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Successfully uninstalled i18n-1.14.1
root@qanteon-proxmox-develop01:~# GEM_HOME=/opt/vagrant/embedded/gems/ gem install i18n --version=='0.6.4'
Fetching i18n-0.6.4.gem
Successfully installed i18n-0.6.4
Parsing documentation for i18n-0.6.4
Installing ri documentation for i18n-0.6.4
Done installing documentation for i18n after 0 seconds
1 gem installed
root@qanteon-proxmox-develop01:~# vagrant plugin install vagrant-proxmox
/opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'i18n' (~> 1.12) - did find: [i18n-0.6.4] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/opt/vagrant/embedded/gems' , execute `gem env` for more information
        from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/dependency.rb:323:in `to_spec'
        from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:95:in `block (2 levels) in <main>'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:94:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:94:in `block in <main>'
        from /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:105:in `<main>'
`
